// index.styles.ts
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#000" },
  inner: { flex: 1, padding: 20 },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
    alignItems: "center",
  },
  header: { color: "#FFF", fontSize: 24, fontWeight: "900" },
  unitPill: {
    flexDirection: "row",
    backgroundColor: "#1A1A1A",
    borderRadius: 25,
    padding: 4,
    width: 110,
  },
  pillBtn: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
    borderRadius: 20,
  },
  pillActive: { backgroundColor: "#00FF00" },
  pillInactive: { backgroundColor: "transparent" },
  pillText: { color: "#444", fontSize: 10, fontWeight: "900" },
  pillTextActive: { color: "#000" },
  viewSelector: {
    flexDirection: "row",
    backgroundColor: "#111",
    borderRadius: 12,
    padding: 4,
    marginBottom: 20,
  },
  viewBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 10,
  },
  viewBtnActive: { backgroundColor: "#222" },
  viewText: { color: "#555", fontSize: 11, fontWeight: "800" },
  viewTextActive: { color: "#FFF" },
  categoryRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 15,
  },
  catBtn: {
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  catBtnActive: { borderBottomColor: "#00FF00" },
  catText: { color: "#444", fontSize: 12, fontWeight: "900" },
  catTextActive: { color: "#00FF00" },
  slidingBarContainer: { height: 40, marginBottom: 20 },
  tab: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#111",
    marginRight: 8,
  },
  tabActive: { backgroundColor: "#FFF" },
  tabText: { color: "#444", fontWeight: "bold", fontSize: 12 },
  tabTextActive: { color: "#000" },
  addTabBtn: {
    paddingHorizontal: 15,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#00FF00",
    marginLeft: 5,
  },
  addTabText: { color: "#00FF00", fontSize: 10, fontWeight: "900" },
  calcCard: {
    backgroundColor: "#121212",
    borderRadius: 30,
    padding: 25,
    borderWidth: 1,
    borderColor: "#222",
    marginBottom: 20,
  },
  inputRow: { flexDirection: "row", justifyContent: "space-between" },
  inputBox: { width: "45%" },
  inputLabel: {
    color: "#444",
    fontSize: 10,
    fontWeight: "900",
    marginBottom: 5,
  },
  input: { fontSize: 38, fontWeight: "bold", color: "#FFF" },
  divider: { height: 1, backgroundColor: "#222", marginVertical: 25 },
  resultRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  resLabel: {
    color: "#00FF00",
    fontSize: 10,
    fontWeight: "900",
    marginBottom: 5,
  },
  resValue: { color: "#FFF", fontSize: 36, fontWeight: "bold" },
  unitSub: { fontSize: 14, color: "#444" },
  plateList: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "600",
    width: 120,
    textAlign: "right",
  },
  logBtn: {
    backgroundColor: "#00FF00",
    padding: 20,
    borderRadius: 20,
    alignItems: "center",
  },
  logBtnText: { color: "#000", fontWeight: "900", fontSize: 16 },
  historyItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#121212",
    padding: 20,
    borderRadius: 20,
    marginBottom: 12,
    alignItems: "center",
  },
  historyDate: { color: "#444", fontSize: 10, marginBottom: 4 },
  historyText: { color: "#FFF", fontSize: 18, fontWeight: "bold" },
  historyMax: { color: "#00FF00", fontWeight: "bold", marginRight: 15 },
  delBtn: {
    backgroundColor: "#222",
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  delBtnText: { color: "#FF4444", fontSize: 12, fontWeight: "bold" },
});

export default styles;
